version: "3"
services:
  app:
    build:
      context: ./docker/app
      args:
        - TZ=${TZ}
    ports:
      - ${APP_PORT}:8000
    volumes:
      - ${PROJECT_PATH}:/var/www
      - ./logs:/var/log/php
      - ./docker/app/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    
